dist: focal
sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "16"
  - "14"
  - "12"
  - "10"
cache: npm
script:
  - "npm run lint"
  - "npm test"
jobs:
  include:
    - stage: npm release
      if: branch = master AND type != pull_request
      node_js: "14"
      script: skip
      after_success:
        - npx semantic-release
branches:
  only:
    - master
